### PR TITLE
Add form type extensions for Carbon

### PR DESCRIPTION
**Pull request by sandermarechal**
This PR implements #4

### CODE REVIEW

**Comment by lightsuner** [comment]
@sandermarechal thank you, you are very fast! The code looks cool. But:
1) Maybe you have time to write few tests?
2) Could you please update readme.md (describe there new feature) ?

Thank you again!

**Comment by sandermarechal** [comment]
If you could update and merge again, I have added a testcase, updated the docs and fixed your PHPunit setup

**Comment by lightsuner** [comment]
@sandermarechal could you please send another one PR?

**Comment by sandermarechal** [comment]
Sure, done!

**Pull request merged**
